[tool.poetry]
name = "xdyna"
version = "0.0.2"
description = "Xsuite dynamics package"
repository = "https://github.com/xsuite/xdyna"
authors = ["Frederik F. Van der Veken <frederik.van.der.veken@cern.ch>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11" # The upper bound is required by scipy
numpy = "^1.22.3"
scipy = "^1.8.0"
pandas = "^1.4.2"
xobjects = "^0.1.12"
xdeps = "^0.0.5"
xpart = "^0.6.1"
xtrack = "^0.11.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyter = "^1.0.0"
ipykernel = "^6.13.0"

[build-system]
requires = ["poetry-core>=1.0.8"]  # Needed for pip install -e
build-backend = "poetry.core.masonry.api"
