import itertools

import h5py
import numpy as np
from numba import njit
from tqdm import tqdm

from .generic_writer import GenericWriter, H5pyWriter, LocalWriter


@njit
def simple_gali(gali_matrix):
    if np.any(np.isnan(gali_matrix)):
        return np.nan
    else:
        _, s, _ = np.linalg.svd(gali_matrix)
        return np.prod(s)


@njit
def gali(gali_matrix):
    gali_matrix = np.transpose(gali_matrix, (2, 0, 1))
    gali = []
    for m in gali_matrix:
        gali.append(simple_gali(m))
    gali = np.asarray(gali)
    return gali


COORD_LIST = ["x", "px", "y", "py", "zeta", "ptau"]
NORM_COORD_LIST = ["x_norm", "px_norm", "y_norm", "py_norm", "zeta_norm", "pzeta_norm"]


def _make_gali_combos(coord_list):
    return {
        "2": list(itertools.combinations(coord_list, 2)),
        "3": list(itertools.combinations(coord_list, 3)),
        "4": list(itertools.combinations(coord_list, 4)),
        "5": list(itertools.combinations(coord_list, 5)),
        "6": list(itertools.combinations(coord_list, 6)),
        "all": list(itertools.combinations(coord_list, 2))
        + list(itertools.combinations(coord_list, 3))
        + list(itertools.combinations(coord_list, 4))
        + list(itertools.combinations(coord_list, 5))
        + list(itertools.combinations(coord_list, 6)),
    }


def gali_extractor(
    input_writer: GenericWriter,
    output_writer: GenericWriter,
    times,
    coord_list=NORM_COORD_LIST,
    which_gali="all",
    custom_combos=None,
    preload_data=False,
):
    """Calculate the Generalized Alignment Index (GALI) for a set of
    coordinates generated by the GhostParticleManager class.

    Parameters
    ----------
    input_writer : GenericWriter
        The writer containing the data to be converted.
    output_writer : GenericWriter
        The writer to which the converted data will be written.
    times : list
        The times at which to calculate GALI.
    coord_list : list, optional
        The coordinates to use in the GALI calculation. Defaults to
        NORM_COORD_LIST.
    which_gali : str, optional
        Which GALI to calculate. Options are '2', '3', '4', '5', '6', 'all',
        and 'custom'. Defaults to 'all'.
    custom_combos : list, optional
        A list of tuples containing the coordinates to use in the GALI
        calculation. Only used if which_gali is 'custom'. Defaults to None.
    preload_data : bool, optional
        Whether to preload the data from the input_writer. Only works if the
        input_writer is an H5pyWriter. Defaults to False.
    """
    if preload_data and not isinstance(input_writer, H5pyWriter):
        raise ValueError("preload_data only works with H5pyWriter")
    elif isinstance(input_writer, H5pyWriter):
        print("preloading data")
        input_writer = input_writer.convert_to_localwriter()

    if custom_combos is not None:
        if which_gali != "custom":
            raise ValueError("which_gali must be 'custom' if using custom_combos")
        combo_list = custom_combos
    else:
        combo_list = _make_gali_combos(coord_list)[which_gali]

    print("evaluating gali")
    for i, combo in enumerate(tqdm(combo_list)):
        for t in tqdm(times):
            dataset_name = f"gali{len(combo)}/{'_'.join(combo)}/{t}"

            gali_matrix = np.asarray(
                [
                    [
                        input_writer.get_data(f"direction/{a}/{x}/{t}")
                        for x in coord_list
                    ]
                    for a in combo
                ]
            )
            disp = gali(gali_matrix)

            output_writer.write_data(dataset_name, data=disp)
